# Copyright 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Install zuul-web.
  hosts: zuul-web
  become: yes

  tasks:
    - name: Setup openstack.zuul role.
      include_role:
        name: openstack.zuul
      vars:
        zuul_task_manager:
          - service
        zuul_file_zuul_web_service_config_manage: true
        zuul_file_zuul_web_service_manage: true
        zuul_service_zuul_web_manage: true

    - name: Re-Config web-logging.conf for disable debug
      ini_file:
        path: /etc/zuul/web-logging.conf
        option: "{{ item.option }}"
        section: "{{ item.section }}"
        value: "{{ item.value }}"
      with_items:
        - { option: "handlers", section: "logger_zuul", value: "normal" }
        - { option: "handlers", section: "logger_gerrit", value: "normal" }
        - { option: "handlers", section: "logger_gear", value: "normal" }
        - { option: "level", section: "handler_debug", value: "INFO" }

    - name: Restart zuul-web services
      service: name=zuul-web state=restarted

    - name: Config zuul web javascript
      shell: |
        ./tools/install-js-tools.sh
        npm install
        if [[ ! -f zuul/web/static/status.html ]]
        then
            mkdir -p zuul/web/static
            pushd web/
                yarn install
                sed -e 's#"homepage": "/"#"homepage": "/zuul/"#' -i package.json
                yarn build
            popd
        fi
      args:
        chdir: '{{ zuul_git_dest }}'
        executable: /bin/bash

    - name: Setup openstack.logrotate role.
      include_role:
        name: openstack.logrotate
      vars:
        logrotate_configs:
          - name: zuul-web
            log: /var/log/zuul/web-debug.log /var/log/zuul/web.log
            options:
              - compress
              - missingok
              - rotate 7
              - daily
              - notifempty
